  main:
    submitUnchanged: true
    fields:
      - name: primary_idle_time
        caption: Primary Idle Time (sec)
        type: spinner
        min: 30
        max: 3600

      - type: checkbox
        name: is_endpoint
        caption: Endpoint to Primary DB
        value: true

  configure:
    submitUnchanged: true
    fields:
      - name: primary_idle_time
        caption: Primary Idle Time (sec)
        type: spinner
        min: 30
        max: 3600

      - type: checkbox
        name: is_endpoint
        caption: Endpoint to Primary DB
        value: true

    onBeforeInit: |
      var envName = '${env.envName}';
      var settings = jps.settings.configure;
      var fields = {}, endpoints;
      for (var i = 0, field; field = jps.settings.configure.fields[i]; i++)
        fields[field.name] = field;
      fields["is_endpoint"].value = false;
      var envInfo = jelastic.env.control.GetEnvInfo(envName, session);
      if (envInfo.result != 0) return envInfo;
    
      var nodes = envInfo.nodes, node;
      for (var i = 0, n = nodes.length; i < n; i++) {
        node = nodes[i];
        if (node.nodeGroup == 'sqldb' && node.endpoints) {
          for (var k = 0, l = node.endpoints.length; k < l; k++) {
            if (node.endpoints[k].name == "PrimaryDB") fields["is_endpoint"].value = true;
          }
        }
      }
      return settings;
